# Generated by Django 4.1.3 on 2022-11-16 13:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_pre_courses_delete_cvonline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='viewers',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.DeleteModel(
            name='UserLessonView',
        ),
    ]
