# Generated by Django 4.1.3 on 2022-11-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='active',
            new_name='like',
        ),
    ]
