# Generated by Django 4.1.3 on 2022-11-17 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_cvonline_userlessonview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='viewers',
            field=models.ManyToManyField(through='courses.UserLessonView', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'lesson')},
        ),
    ]
